name: RDP-Debian (xrdp + Tailscale)
on:
  workflow_dispatch:

jobs:
  secure-rdp-debian:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    env:
      USERNAME: rdpuser

    steps:
      - name: Set up and install packages
        run: |
          set -euo pipefail
          sudo apt-get update
          # instalar desktop leve e xrdp
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils xrdp
          # opcional: instalar utilitários
          sudo apt-get install -y net-tools iproute2 procps curl sudo ca-certificates

      - name: Create user and set strong password
        id: create_user
        run: |
          set -euo pipefail
          # gera senha complexa (32 chars)
          PASSWORD=$(openssl rand -base64 24)
          sudo useradd -m -s /bin/bash ${USERNAME}
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          sudo usermod -aG sudo ${USERNAME}
          echo "RDP_CREDS=User: ${USERNAME} | Password: ${PASSWORD}" >> $GITHUB_ENV
          # verify
          id ${USERNAME}

      - name: Configure xrdp to use xfce
        run: |
          set -euo pipefail
          # ensure xfce session for xrdp
          sudo bash -c 'echo "startxfce4" > /home/'"${USERNAME}"'/.xsession'
          sudo chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.xsession
          # sometimes needed for display
          sudo sed -i.bak '/^new_cursors=/d' /etc/xrdp/xrdp.ini || true
          sudo systemctl enable --now xrdp

      - name: Install Tailscale
        run: |
          set -euo pipefail
          # install tailscale (official install script)
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo systemctl enable --now tailscaled

      - name: Bring up Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${TAILSCALE_AUTH_KEY:-}" ]; then
            echo "TAILSCALE_AUTH_KEY is empty"; exit 1
          fi
          sudo tailscale up --authkey="${TAILSCALE_AUTH_KEY}" --hostname=gh-runner-${GITHUB_RUN_ID} || (sudo tailscale up --authkey="${TAILSCALE_AUTH_KEY}" && true)
          # wait and capture IP
          for i in {1..12}; do
            TS_IP=$(tailscale ip -4 2>/dev/null || true)
            if [ -n "${TS_IP:-}" ]; then break; fi
            sleep 5
          done
          if [ -z "${TS_IP:-}" ]; then
            echo "Tailscale IP not assigned"; exit 1
          fi
          echo "TAILSCALE_IP=${TS_IP}" >> $GITHUB_ENV

      - name: Open firewall (ufw) for 3389 on runner (best-effort)
        run: |
          set -euo pipefail
          # many runners do not run ufw; this is best-effort
          if command -v ufw >/dev/null 2>&1; then
            sudo ufw allow 3389/tcp || true
          else
            # fallback: use iptables to allow local access
            sudo iptables -I INPUT -p tcp --dport 3389 -j ACCEPT || true
          fi

      - name: Verify connection and report
        run: |
          set -euo pipefail
          echo "=== RDP ACCESS INFO ==="
          echo "Tailscale IP: ${{ env.TAILSCALE_IP }}"
          echo "Username: ${{ env.USERNAME }}"
          echo "Password: ${RDP_CREDS##*Password: }"
          echo "======================="
          # verify xrdp listening
          ss -ltnp | grep -E ':3389\b' || true

      - name: Keep runner alive (blocking)
        run: |
          echo "Keeping runner alive. Logs will show the RDP info above."
          # loop to keep job running (Ctrl+C in Actions UI to cancel)
          while true; do date; sleep 300; done
